SilverStripe\CMS\Model\SiteTree:
  extensions:
    WorkflowExtension: AdrHumphreys\Workflow\WorkflowExtension

DNADesign\Elemental\Models\BaseElement:
  extensions:
    WorkflowExtension: AdrHumphreys\Workflow\WorkflowExtension
